name: Build
permissions: {}
on:
  push:
#    paths-ignore:
#    - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build
      run: yarn build
    - uses: actions/upload-artifact@v4
      with:
        name: homed-zigbee-networkmap
        path: ./dist/homed-zigbee-networkmap.js
